### ISSUE TITLE
Function .centers() returns only 3 items

### ISSUE THREAD

**Issue by matti9410** [d3/d3-hexbin#15]
Hello :)
I wanna use .centers() but when i use this I get only 3 points 

> 0: [0, 0]
1: [1.7320508075688772, 0]
2: [0.8660254037844386, 1.5]

Why visible and not visible hexagon centers points is not return ?

**Comment by Fil** [comment]
You should probably set the hexbin's .extent() before calling .centers()

See https://github.com/d3/d3-hexbin#hexbin_centers
