### ISSUE TITLE
implicit dependency on d3

### ISSUE THREAD

**Issue by MoritzStefaner** [d3/d3-hexbin#2]
Line 43 hexbin.js: use of "d3.values" lets to an error if d3.js is not present, is there any equivalent in a smaller d3 module?

**Comment by ghost** [comment]
Hey @MoritzStefaner, great catch! 
This accidentally got left behind as I was porting the package over.

I think it has been fixed now as `values` is part of the `d3-array` package, but I am leaving this issue open. 

If you could confirm that would be awesome! Thanks :)

**Comment by MoritzStefaner** [comment]
Yes, perfect! That does it. Thanks for the quick reply.
